default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  #database: myapp_development
  username: postgres
  password: postgres
  host: localhost

test:
  <<: *default
  database: myapp_test
  username: postgres
  password: postgres
  host: localhost

production:
  adapter: postgresql
  database: patient_management_production
  username: ubuntu
  password: postgres
  host: localhost
  port: 5432